# fly.toml app configuration file generated for mediafusion-polished-glitter-1665 on 2024-01-27T21:32:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mediafusion-polished-glitter-1665'
primary_region = 'yyz'

[build]
  builder = 'paketobuildpacks/builder:full'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
