name: Deploy Docker image to GitHub Container Registry

on:
  push:
    branches:
      - prowlarr_custom_deployment

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short SHA
        id: short_sha
        run: echo "GIT_REV=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployment/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: GIT_REV=${{ env.GIT_REV }}
          tags: |
            ghcr.io/ragmehos/mf:v${{ github.ref_name }}
            ghcr.io/ragmehos/mf:latest
